"""
Mock Inference Worker - for local testing without actual model
This simulates the inference::run_inference function without needing PyTorch/model loading
Use this locally, replace with real version for production
"""
import os
import time
from typing import Any, Dict, List

from iii import InitOptions, Logger, register_worker

iii = register_worker(
    os.environ.get("III_URL", "ws://localhost:49134"),
    InitOptions(worker_name="inference-worker"),
)
logger = Logger()

# Mock responses - simulating actual inference results
MOCK_RESPONSES = {
    "hello": "Hello! I'm an AI assistant. How can I help you today?",
    "what is ai": "AI (Artificial Intelligence) refers to computer systems designed to perform tasks that typically require human intelligence, such as learning, reasoning, problem-solving, and natural language understanding.",
    "explain": "I'd be happy to explain! Could you be more specific about what you'd like me to explain?",
    "default": "This is a simulated response from the inference worker. In production, this would be generated by the Gemma 3 270M language model."
}

def run_inference_handler(payload: Dict[str, str | List[Dict[str, Any]]]) -> str:
    """
    Mock inference handler - simulates the actual inference process
    
    Args:
        payload: Dict with 'messages' key containing conversation history
        
    Returns:
        String response simulating model output
    """
    messages = payload.get("messages", [])
    
    logger.info(f"Mock inference called with {len(messages)} messages")
    
    # Extract the last user message to determine response
    user_message = ""
    if messages:
        for msg in reversed(messages):
            if msg.get("role") == "user":
                user_message = msg.get("content", "").lower()
                break
    
    # Simple logic to pick response
    response = MOCK_RESPONSES.get("default")
    for keyword, mock_response in MOCK_RESPONSES.items():
        if keyword in user_message:
            response = mock_response
            break
    
    # Simulate processing time
    time.sleep(0.5)
    
    logger.info(f"Returning mock response: {response[:50]}...")
    return response

# Register the function so caller-worker can call it
iii.register_function("inference::run_inference", run_inference_handler)

logger.info("✅ Mock Inference Worker started - listening for RPC calls on ws://localhost:49134")
print("Mock Inference Worker started - listening for calls")
